### ISSUE TITLE
Determine the path of tar before using it

### ISSUE THREAD

**Issue by fkautz** [fastai/swiftai#6]
https://github.com/fastai/harebrain/blob/master/Sources/Harebrain/08_data_block.swift assumes tar is located at /bin/tar but it is sometimes located at /usr/bin/tar and may exist in other non-standardized locations on other systems.

We should identify where tar is on the path before using it, or use a library designed to untar.

**Comment by jph00** [comment]
Sounds good! Would you like to try a PR that does that?

**Comment by fkautz** [comment]
Sure, I'll put something together soon.
